name: Web Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.5  # Выберите нужную версию Python

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pytest  # Установите pytest
        pip install --upgrade selenium

    - name: Install ChromeDriver
      run: |
        # Удалить существующий chromedriver (если есть)
        sudo rm /usr/local/bin/chromedriver
        # Установить совместимую версию ChromeDriver
        CHROMEDRIVER_VERSION=118.0.5993.70  # Версия совместимого ChromeDriver
        wget -N https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip -P /tmp/
        unzip /tmp/chromedriver_linux64.zip -d /usr/local/bin/
        chmod +x /usr/local/bin/chromedriver
        # Установить Chrome
        sudo apt-get update
        sudo apt-get install -y chromium-chromedriver
        google-chrome --version
        chromedriver --version



    - name: Run Web Tests
      run: pytest -s -v 

    - name: Publish Test Results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: .
