name: Web Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.5  # Выберите нужную версию Python

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pytest  # Установите pytest
        pip install --upgrade selenium
        # # Проверка на существование /usr/bin/chromedriver и его удаление, если он существует
        # if [ -f /usr/bin/chromedriver ]; then
        #   sudo rm /usr/bin/chromedriver
        # fi
        # # Установка Chrome
        # sudo apt-get install -y google-chrome-stable
        # google-chrome --version
        # chromedriver --version

    - name: Install ChromeDriver
      run: |
        CHROMEDRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE)
        wget -N https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip -P /tmp/
        unzip /tmp/chromedriver_linux64.zip -d /usr/local/bin/
        chmod +x /usr/local/bin/chromedriver



    - name: Run Web Tests
      run: pytest -s -v 

    - name: Publish Test Results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: .
